const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const out = path.join(__dirname, 'artifacts', 'projects-editing');
const cache = page => page.evaluate(() => JSON.parse(localStorage.getItem('forma:workspace:v1:guest')).workspace);
(async () => {
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_EXECUTABLE_PATH ? { executablePath: process.env.PLAYWRIGHT_EXECUTABLE_PATH } : {}) });
  try {
    const page = await browser.newPage({ viewport: { width: 1512, height: 982 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(process.env.APP_URL || 'http://127.0.0.1:5180');
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    await page.locator('.new-project-card').click();
    await page.getByLabel('Projektnamn', { exact: true }).fill('Ett redigerbart projekt');
    await page.getByLabel('Beskrivning', { exact: true }).fill('Planera nästa steg och fortsätt redigera huvuduppgifter och deluppgifter när planen ändras.');
    await page.getByLabel('Huvuduppgift', { exact: true }).fill('Planera första steget');
    await page.getByLabel('Deluppgifter', { exact: true }).fill('Skriv ner målet\nVälj en deadline');
    await page.getByRole('button', { name: 'Skapa projekt', exact: true }).click();
    const before = structuredClone((await cache(page)).tasks);
    const box = await page.getByRole('dialog').boundingBox();
    assert.ok(box.width >= 1000 && box.width <= 1432, `Desktop project width: ${box.width}`);
    const overview = await page.locator('.project-overview').boundingBox();
    const work = await page.locator('.project-work').boundingBox();
    assert.ok(work.x > overview.x + overview.width, 'Desktop overview and tasks sit side by side.');
    await page.screenshot({ path: path.join(out, 'desktop-project.png'), animations: 'disabled' });
    await page.getByRole('button', { name: 'Redigera deluppgift Skriv ner målet', exact: true }).click();
    assert.equal(await page.getByLabel('Deluppgift 1', { exact: true }).evaluate(input => input === document.activeElement), true);
    await page.getByLabel('Deluppgift 1', { exact: true }).fill('Ett tydligare mål');
    await page.getByLabel('Titel', { exact: true }).fill('Planera nästa steg');
    await page.getByLabel('Ny deluppgift', { exact: true }).fill('Boka en tid');
    await page.getByRole('button', { name: 'Lägg till deluppgift', exact: true }).click();
    await page.getByRole('button', { name: 'Ta bort Välj en deadline', exact: true }).click();
    await page.getByRole('checkbox', { name: 'Markera Ett tydligare mål som klar', exact: true }).check();
    await page.screenshot({ path: path.join(out, 'desktop-editor.png'), animations: 'disabled' });
    await page.getByRole('button', { name: 'Spara uppgift', exact: true }).click();
    const saved = (await cache(page)).projects.find(project => project.title === 'Ett redigerbart projekt').tasks[0];
    assert.equal(saved.title, 'Planera nästa steg');
    assert.deepEqual(saved.checklist.map(item => item.title), ['Ett tydligare mål', 'Boka en tid']);
    assert.equal(saved.checklist[0].completed, true);
    assert.deepEqual((await cache(page)).tasks, before);
    await page.getByRole('button', { name: 'Redigera huvuduppgift Planera nästa steg', exact: true }).click();
    await page.getByLabel('Deluppgift 1', { exact: true }).fill('Osparad text');
    await page.getByRole('button', { name: 'Avbryt', exact: true }).click();
    assert.deepEqual((await cache(page)).projects.find(project => project.title === 'Ett redigerbart projekt').tasks[0], saved);
    await page.reload();
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    await page.getByRole('button', { name: 'Öppna projekt Ett redigerbart projekt', exact: true }).click();
    await page.getByRole('button', { name: 'Redigera deluppgift Boka en tid', exact: true }).click();
    assert.equal(await page.getByLabel('Deluppgift 2', { exact: true }).inputValue(), 'Boka en tid');
    assert.equal(await page.getByLabel('Deluppgift 2', { exact: true }).evaluate(input => input === document.activeElement), true);
    await page.getByLabel('Deluppgift 2', { exact: true }).fill('   ');
    await page.getByRole('button', { name: 'Spara uppgift', exact: true }).click();
    await page.getByRole('alert').getByText('Ange en titel för varje deluppgift.', { exact: true }).waitFor();
    assert.deepEqual((await cache(page)).projects.find(project => project.title === 'Ett redigerbart projekt').tasks[0], saved);
    await page.getByRole('button', { name: 'Avbryt', exact: true }).click();
    for (const width of [834, 440, 320]) {
      await page.setViewportSize({ width, height: 900 });
      const bounds = await page.getByRole('dialog').boundingBox();
      assert.ok(bounds.width <= width && bounds.x >= 0);
      assert.ok(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth + 1));
      await page.screenshot({ path: path.join(out, `project-${width}.png`), animations: 'disabled' });
      await page.getByRole('button', { name: 'Redigera deluppgift Boka en tid', exact: true }).click();
      assert.ok(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth + 1));
      await page.getByLabel('Deluppgift 2', { exact: true }).fill(`Ny tid på ${width}`);
      await page.getByRole('button', { name: 'Spara uppgift', exact: true }).click();
      await page.getByRole('button', { name: `Redigera deluppgift Ny tid på ${width}`, exact: true }).waitFor();
      await page.getByRole('button', { name: `Redigera deluppgift Ny tid på ${width}`, exact: true }).click();
      await page.getByLabel('Deluppgift 2', { exact: true }).fill('Boka en tid');
      await page.screenshot({ path: path.join(out, `editor-${width}.png`), animations: 'disabled' });
      await page.getByRole('button', { name: 'Spara uppgift', exact: true }).click();
    }
    assert.deepEqual(errors, []);
    console.log('PASS Project editing: rename main/subtasks, focused entry, add/remove, cancel, validation, reload, independent Kanban and 1512/834/440/320 px layouts.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
